// website/src/components/InputLabel.tsx
import { component$ } from '@qwik.dev/core';
import clsx from 'clsx';

type InputLabelProps = {
  component?: 'label' | 'legend' | 'div';
  name?: string;
  label?: string;
  required?: boolean;
  margin?: 'none';
};

/**
 * Input label for a form field.
 */
export const InputLabel = component$(
  ({ component, name, label, required, margin }: InputLabelProps) => {
    const Element = component ?? (name ? 'label' : 'div');
    return (
      <>
        {label && (
          <Element
            class={clsx(
              'inline-block font-medium md:text-lg lg:text-xl',
              !margin && 'mb-4 lg:mb-5'
            )}
            for={name}
          >
            {label}{' '}
            {required && (
              <span class="ml-1 text-red-600 dark:text-red-400">*</span>
            )}
          </Element>
        )}
      </>
    );
  }
);

// playgrounds/react/src/components/InputLabel.tsx
import clsx from 'clsx';

type InputLabelProps = {
  component?: 'label' | 'legend' | 'div';
  name?: string;
  label?: string;
  required?: boolean;
  margin?: 'none';
};

/**
 * Input label for a form field.
 */
export function InputLabel({
  component,
  name,
  label,
  required,
  margin,
}: InputLabelProps) {
  const Element = component ?? (name ? 'label' : 'div');
  return (
    <>
      {label && (
        <Element
          className={clsx(
            'inline-block font-medium md:text-lg lg:text-xl',
            !margin && 'mb-4 lg:mb-5'
          )}
          htmlFor={name}
        >
          {label}{' '}
          {required && (
            <span className="ml-1 text-red-600 dark:text-red-400">*</span>
          )}
        </Element>
      )}
    </>
  );
}
