// playgrounds/angular/src/components/input-errors.component.ts
import { Component, input } from '@angular/core';
import { ExpandableComponent } from './expandable.component.ts';

/**
 * Input error that tells the user what to do to fix the problem.
 */
@Component({
  selector: 'app-input-errors',
  standalone: true,
  imports: [ExpandableComponent],
  template: `
    <app-expandable [expanded]="!!errors()">
      <div
        [id]="name() + '-error'"
        class="pt-4 text-sm text-red-500 md:text-base lg:pt-5 lg:text-lg dark:text-red-400"
      >
        {{ errors()?.[0] }}
      </div>
    </app-expandable>
  `,
})
export class InputErrorsComponent {
  readonly name = input.required<string>();
  readonly errors = input<[string, ...string[]] | null>(null);
}

// playgrounds/react/src/components/InputErrors.tsx
import { Expandable } from './Expandable';

type InputErrorProps = {
  name: string;
  errors: [string, ...string[]] | null;
};

/**
 * Input error that tells the user what to do to fix the problem.
 */
export function InputErrors({ name, errors }: InputErrorProps) {
  return (
    <Expandable expanded={!!errors}>
      <div
        className="pt-4 text-sm text-red-500 md:text-base lg:pt-5 lg:text-lg dark:text-red-400"
        id={`${name}-error`}
      >
        {errors?.[0]}
      </div>
    </Expandable>
  );
}
