// playgrounds/angular/src/components/select.component.ts
import { Component, computed, input } from '@angular/core';
import { type FieldStore, FormischControl } from '@formisch/angular';
import clsx from 'clsx';
import { AngleDownIconComponent } from '../icons/angle-down-icon.component.ts';
import { InputErrorsComponent } from './input-errors.component.ts';
import { InputLabelComponent } from './input-label.component.ts';

interface SelectOption {
  label: string;
  value: string;
}

/**
 * Select field that allows users to select predefined values. Various
 * decorations can be displayed in or around the field to communicate the
 * entry requirements.
 */
@Component({
  selector: 'app-select',
  standalone: true,
  host: { class: 'block' },
  imports: [
    InputLabelComponent,
    InputErrorsComponent,
    AngleDownIconComponent,
    FormischControl,
  ],
  template: `
    <div [class]="containerClasses()">
      <app-input-label
        [name]="field().name()"
        [label]="label()"
        [required]="required()"
      />
      <div class="relative flex items-center">
        <select
          [id]="field().name()"
          [multiple]="!!multiple()"
          [required]="!!required()"
          [class]="selectClasses()"
          [attr.size]="size()"
          [attr.aria-invalid]="!!field().errors()"
          [attr.aria-errormessage]="
            field().errors() ? field().name() + '-error' : null
          "
          [formischControl]="field()"
        >
          <option value="" disabled hidden [selected]="!values().length">
            {{ placeholder() }}
          </option>
          @for (option of options(); track option.value) {
            <option [value]="option.value">
              {{ option.label }}
            </option>
          }
        </select>
        @if (!multiple()) {
          <app-angle-down-icon
            class="pointer-events-none absolute right-6 h-5 lg:right-8 lg:h-6"
          />
        }
      </div>
      <app-input-errors [name]="field().name()" [errors]="field().errors()" />
    </div>
  `,
})
export class SelectComponent {
  readonly field = input.required<FieldStore>();
  readonly label = input<string>();
  readonly options = input.required<SelectOption[]>();
  readonly multiple = input<boolean>(false);
  readonly size = input<number>();
  readonly placeholder = input<string>();
  readonly required = input<boolean>(false);
  readonly class = input<string>('');

  protected readonly values = computed<string[]>(() => {
    const value = this.field().input();
    if (Array.isArray(value)) {
      return value as string[];
    }
    if (value && typeof value === 'string') {
      return [value];
    }
    return [];
  });

  protected readonly containerClasses = () =>
    clsx('px-8 lg:px-10', this.class());

  protected readonly selectClasses = computed(() =>
    clsx(
      'w-full appearance-none space-y-2 rounded-2xl border-2 bg-transparent px-5 outline-none md:text-lg lg:space-y-3 lg:px-6 lg:text-xl',
      this.field().errors()
        ? 'border-red-600/50 dark:border-red-400/50'
        : 'border-slate-200 hover:border-slate-300 focus:border-sky-600/50 dark:border-slate-800 dark:hover:border-slate-700 dark:focus:border-sky-400/50',
      this.multiple() ? 'py-5' : 'h-14 md:h-16 lg:h-[70px]',
      this.placeholder() && !this.values().length && 'text-slate-500'
    )
  );
}

// playgrounds/react/src/components/Select.tsx
import type { FieldElementProps } from '@formisch/react';
import clsx from 'clsx';
import { useMemo } from 'react';
import { AngleDownIcon } from '../icons';
import { InputErrors } from './InputErrors';
import { InputLabel } from './InputLabel';

interface SelectProps extends FieldElementProps {
  className?: string;
  label?: string;
  options: { label: string; value: string }[];
  multiple?: boolean;
  size?: number;
  placeholder?: string;
  required?: boolean;
  input: string | string[] | null | undefined;
  errors: [string, ...string[]] | null;
}

/**
 * Select field that allows users to select predefined values. Various
 * decorations can be displayed in or around the field to communicate the
 * entry requirements.
 */
export function Select({
  options,
  label,
  input,
  errors,
  className,
  ...props
}: SelectProps) {
  const { name, required, multiple, placeholder } = props;

  // Create computed value of selected values
  const values = useMemo(
    () =>
      Array.isArray(input)
        ? input
        : input && typeof input === 'string'
          ? [input]
          : [],
    [input]
  );

  return (
    <div className={clsx('px-8 lg:px-10', className)}>
      <InputLabel name={name} label={label} required={required} />
      <div className="relative flex items-center">
        <select
          {...props}
          className={clsx(
            'w-full appearance-none space-y-2 rounded-2xl border-2 bg-transparent px-5 outline-none md:text-lg lg:space-y-3 lg:px-6 lg:text-xl',
            errors
              ? 'border-red-600/50 dark:border-red-400/50'
              : 'border-slate-200 hover:border-slate-300 focus:border-sky-600/50 dark:border-slate-800 dark:hover:border-slate-700 dark:focus:border-sky-400/50',
            multiple ? 'py-5' : 'h-14 md:h-16 lg:h-[70px]',
            placeholder && !values?.length && 'text-slate-500'
          )}
          id={name}
          value={multiple ? values : values[0] || ''}
          aria-invalid={!!errors}
          aria-errormessage={`${name}-error`}
        >
          <option value="" disabled hidden>
            {placeholder}
          </option>
          {options.map(({ label, value }) => (
            <option key={value} value={value}>
              {label}
            </option>
          ))}
        </select>
        {!multiple && (
          <AngleDownIcon className="pointer-events-none absolute right-6 h-5 lg:right-8 lg:h-6" />
        )}
      </div>
      <InputErrors name={name} errors={errors} />
    </div>
  );
}
