// playgrounds/qwik/src/components/RadioGroup.tsx
import type { FieldElementProps, ReadonlySignal } from '@formisch/qwik';
import { component$ } from '@qwik.dev/core';
import clsx from 'clsx';
import { InputErrors } from './InputErrors';
import { InputLabel } from './InputLabel';
import { Radio } from './Radio';

interface RadioGroupProps extends FieldElementProps {
  class?: string;
  label?: string;
  options: { label: string; value: string }[];
  required?: boolean;
  input: ReadonlySignal<string | undefined>;
  errors: ReadonlySignal<[string, ...string[]] | null>;
}

/**
 * Radio group that allows users to select a single option from a list.
 * Uses fieldset and legend for proper HTML semantics and accessibility.
 */
export const RadioGroup = component$(
  ({ label, options, input, errors, ...props }: RadioGroupProps) => {
    const { name, required } = props;
    return (
      <fieldset
        class={clsx('px-8 lg:px-10', props.class)}
        aria-invalid={!!errors?.value}
        aria-errormessage={`${name}-error`}
      >
        <InputLabel component="legend" label={label} required={required} />
        <div class="flex flex-wrap gap-6 rounded-2xl border-2 border-slate-200 p-6 lg:gap-10 lg:p-10 dark:border-slate-800">
          {options.map(({ label, value }) => (
            <Radio
              {...props}
              key={value}
              label={label}
              value={value}
              checked={input.value === value}
            />
          ))}
        </div>
        <InputErrors name={name} errors={errors} />
      </fieldset>
    );
  }
);

// playgrounds/react-native/components/RadioGroup.tsx
import type { FieldElementProps } from '@formisch/react-native';
import { clsx } from 'clsx';
import { View } from 'react-native';
import { InputErrors } from './InputErrors.tsx';
import { InputLabel } from './InputLabel.tsx';
import { Radio } from './Radio.tsx';

interface RadioGroupProps extends FieldElementProps {
  className?: string;
  label?: string;
  options: { label: string; value: string }[];
  required?: boolean;
  input: string | undefined;
  errors: [string, ...string[]] | null;
  onValueChange: (input: string) => void;
}

/**
 * Radio group that allows users to select a single option from a list.
 *
 * Hint: Unlike the DOM playgrounds the selected value is passed explicitly
 * via `onValueChange`, as React Native has no radio element whose state could
 * be read from a change event.
 */
export function RadioGroup({
  label,
  options,
  input,
  errors,
  className,
  required,
  onValueChange,
  ref,
  onFocus,
}: RadioGroupProps) {
  return (
    <View
      className={clsx('px-8 lg:px-10', className)}
      ref={ref}
      role="radiogroup"
      aria-invalid={!!errors}
    >
      <InputLabel label={label} required={required} />
      <View className="flex-row flex-wrap gap-6 rounded-2xl border-2 border-slate-200 p-6 lg:gap-10 lg:p-10 dark:border-slate-800">
        {options.map(({ label, value }) => (
          <Radio
            key={value}
            label={label}
            checked={input === value}
            onPress={() => {
              // Mark the field as touched, as press does not trigger focus
              onFocus();
              onValueChange(value);
            }}
          />
        ))}
      </View>
      <InputErrors errors={errors} />
    </View>
  );
}
