// playgrounds/angular/src/components/radio-group.component.ts
import { Component, input } from '@angular/core';
import type { FieldStore } from '@formisch/angular';
import clsx from 'clsx';
import { InputErrorsComponent } from './input-errors.component.ts';
import { InputLabelComponent } from './input-label.component.ts';
import { RadioComponent } from './radio.component.ts';

interface RadioOption {
  label: string;
  value: string;
}

/**
 * Radio group that allows users to select a single option from a list.
 * Uses fieldset and legend for proper HTML semantics and accessibility.
 */
@Component({
  selector: 'app-radio-group',
  standalone: true,
  host: { class: 'block' },
  imports: [InputLabelComponent, InputErrorsComponent, RadioComponent],
  template: `
    <fieldset
      [class]="containerClasses()"
      [attr.aria-invalid]="!!field().errors()"
      [attr.aria-errormessage]="
        field().errors() ? field().name() + '-error' : null
      "
    >
      <app-input-label
        component="legend"
        [label]="label()"
        [required]="required()"
      />
      <div
        class="flex flex-wrap gap-6 rounded-2xl border-2 border-slate-200 p-6 lg:gap-10 lg:p-10 dark:border-slate-800"
      >
        @for (option of options(); track option.value) {
          <app-radio
            [field]="field()"
            [label]="option.label"
            [value]="option.value"
          />
        }
      </div>
      <app-input-errors [name]="field().name()" [errors]="field().errors()" />
    </fieldset>
  `,
})
export class RadioGroupComponent {
  readonly field = input.required<FieldStore<any, any>>();
  readonly label = input<string>();
  readonly options = input.required<RadioOption[]>();
  readonly required = input<boolean>(false);
  readonly class = input<string>('');

  protected readonly containerClasses = () =>
    clsx('px-8 lg:px-10', this.class());
}

// playgrounds/qwik/src/components/RadioGroup.tsx
import type { FieldElementProps } from '@formisch/qwik';
import { component$, Signal } from '@qwik.dev/core';
import clsx from 'clsx';
import { InputErrors } from './InputErrors';
import { InputLabel } from './InputLabel';
import { Radio } from './Radio';

interface RadioGroupProps extends FieldElementProps {
  class?: string;
  label?: string;
  options: { label: string; value: string }[];
  required?: boolean;
  input: Readonly<Signal<string | undefined>>;
  errors: Readonly<Signal<[string, ...string[]] | null>>;
}

/**
 * Radio group that allows users to select a single option from a list.
 * Uses fieldset and legend for proper HTML semantics and accessibility.
 */
export const RadioGroup = component$(
  ({ label, options, input, errors, ...props }: RadioGroupProps) => {
    const { name, required } = props;
    return (
      <fieldset
        class={clsx('px-8 lg:px-10', props.class)}
        aria-invalid={!!errors?.value}
        aria-errormessage={`${name}-error`}
      >
        <InputLabel component="legend" label={label} required={required} />
        <div class="flex flex-wrap gap-6 rounded-2xl border-2 border-slate-200 p-6 lg:gap-10 lg:p-10 dark:border-slate-800">
          {options.map(({ label, value }) => (
            <Radio
              {...props}
              key={value}
              label={label}
              value={value}
              checked={input.value === value}
            />
          ))}
        </div>
        <InputErrors name={name} errors={errors} />
      </fieldset>
    );
  }
);
