// playgrounds/solid/src/components/Radio.tsx
import type { FieldElementProps } from '@formisch/solid';
import clsx from 'clsx';
import { Show, splitProps } from 'solid-js';
import { InputErrors } from './InputErrors';

interface RadioProps extends FieldElementProps {
  class?: string;
  label?: string;
  value?: string;
  input: boolean | undefined;
  required?: boolean;
  errors: [string, ...string[]] | null;
}

/**
 * Radio button that allows users to select an option. The label next to the
 * radio button describes the selection option.
 */
export function Radio(props: RadioProps) {
  const [, inputProps] = splitProps(props, [
    'class',
    'label',
    'input',
    'errors',
  ]);

  return (
    <div class={clsx('px-8 lg:px-10', props.class)}>
      <label class="flex space-x-4 font-medium select-none md:text-lg lg:text-xl">
        <input
          {...inputProps}
          class="mt-1 h-4 w-4 cursor-pointer lg:mt-1 lg:h-5 lg:w-5"
          type="radio"
          id={props.name}
          value={props.value}
          checked={props.input}
          aria-invalid={!!props.errors}
          aria-errormessage={`${props.name}-error`}
        />
        <span>{props.label}</span>{' '}
        <Show when={props.required}>
          <span class="ml-1 text-red-600 dark:text-red-400">*</span>
        </Show>
      </label>
      <InputErrors name={props.name} errors={props.errors} />
    </div>
  );
}

// playgrounds/qwik/src/components/Radio.tsx
import type { FieldElementProps } from '@formisch/qwik';
import { component$, ReadonlySignal } from '@qwik.dev/core';
import clsx from 'clsx';
import { InputErrors } from './InputErrors';

interface RadioProps extends FieldElementProps {
  class?: string;
  label?: string;
  value?: string;
  input: ReadonlySignal<boolean | undefined>;
  required?: boolean;
  errors: ReadonlySignal<[string, ...string[]] | null>;
}

/**
 * Radio button that allows users to select an option. The label next to the
 * radio button describes the selection option.
 */
export const Radio = component$(
  ({ label, value, input, errors, ...props }: RadioProps) => {
    const { name, required } = props;
    return (
      <div class={clsx('px-8 lg:px-10', props.class)}>
        <label class="flex space-x-4 font-medium select-none md:text-lg lg:text-xl">
          <input
            {...props}
            class="mt-1 h-4 w-4 cursor-pointer lg:mt-1 lg:h-5 lg:w-5"
            type="radio"
            id={name}
            value={value}
            checked={input.value}
            aria-invalid={!!errors?.value}
            aria-errormessage={`${name}-error`}
          />
          <span>{label}</span>{' '}
          {required && (
            <span class="ml-1 text-red-600 dark:text-red-400">*</span>
          )}
        </label>
        <InputErrors name={name} errors={errors} />
      </div>
    );
  }
);
