// playgrounds/react-native/components/Select.tsx
import type { FieldElementProps } from '@formisch/react-native';
import { clsx } from 'clsx';
import { useMemo } from 'react';
import { Pressable, Text, View } from 'react-native';
import { InputErrors } from './InputErrors.tsx';
import { InputLabel } from './InputLabel.tsx';

interface SelectProps<TValue extends string, TMultiple extends boolean>
  extends FieldElementProps {
  className?: string;
  label?: string;
  options: { label: string; value: TValue }[];
  multiple?: TMultiple;
  required?: boolean;
  input: string | string[] | null | undefined;
  errors: [string, ...string[]] | null;
  onValueChange: (input: TMultiple extends true ? TValue[] : TValue) => void;
}

/**
 * Select field that allows users to select predefined values.
 *
 * Hint: Unlike the DOM playgrounds the options are rendered as a pressable
 * list and the new value is passed explicitly via `onValueChange`, as React
 * Native has no select element.
 */
export function Select<
  TValue extends string,
  TMultiple extends boolean = false,
>({
  options,
  label,
  input,
  errors,
  className,
  multiple,
  required,
  onValueChange,
  ref,
  onFocus,
}: SelectProps<TValue, TMultiple>) {
  // Create computed value of selected values
  const values = useMemo(
    () =>
      Array.isArray(input)
        ? input
        : input && typeof input === 'string'
          ? [input]
          : [],
    [input]
  );

  return (
    <View className={clsx('px-8 lg:px-10', className)} ref={ref}>
      <InputLabel label={label} required={required} />
      <View
        className={clsx(
          'rounded-2xl border-2',
          errors
            ? 'border-red-600/50 dark:border-red-400/50'
            : 'border-slate-200 hover:border-slate-300 dark:border-slate-800 dark:hover:border-slate-700'
        )}
        aria-invalid={!!errors}
      >
        {options.map(({ label, value }, index) => {
          const selected = values.includes(value);
          return (
            <Pressable
              key={value}
              className={clsx(
                'h-14 flex-row items-center justify-between px-5 md:h-16 lg:h-[70px] lg:px-6',
                index > 0 &&
                  'border-t-2 border-t-slate-200 dark:border-t-slate-800'
              )}
              role={multiple ? 'checkbox' : 'radio'}
              aria-checked={selected}
              onPress={() => {
                // Mark the field as touched, as press does not trigger focus
                onFocus();
                // Hint: The cast is required because TypeScript cannot narrow
                // the generic conditional type by the runtime `multiple` check
                onValueChange(
                  (multiple
                    ? selected
                      ? values.filter((item) => item !== value)
                      : [...values, value]
                    : value) as TMultiple extends true ? TValue[] : TValue
                );
              }}
            >
              <Text
                className={clsx(
                  'font-lexend md:text-lg lg:text-xl',
                  selected
                    ? 'text-sky-600 dark:text-sky-400'
                    : 'text-slate-600 dark:text-slate-400'
                )}
              >
                {label}
              </Text>
              {selected && (
                <Text className="font-bold text-sky-600 md:text-lg lg:text-xl dark:text-sky-400">
                  ✓
                </Text>
              )}
            </Pressable>
          );
        })}
      </View>
      <InputErrors errors={errors} />
    </View>
  );
}

// playgrounds/qwik/src/components/Select.tsx
import type { FieldElementProps, ReadonlySignal } from '@formisch/qwik';
import { component$, useComputed$ } from '@qwik.dev/core';
import clsx from 'clsx';
import { AngleDownIcon } from '~/icons';
import { InputErrors } from './InputErrors';
import { InputLabel } from './InputLabel';

interface SelectProps extends FieldElementProps {
  class?: string;
  label?: string;
  options: { label: string; value: string }[];
  multiple?: boolean;
  size?: number;
  placeholder?: string;
  required?: boolean;
  input: ReadonlySignal<string | string[] | null | undefined>;
  errors: ReadonlySignal<[string, ...string[]] | null>;
}

/**
 * Select field that allows users to select predefined values. Various
 * decorations can be displayed in or around the field to communicate the
 * entry requirements.
 */
export const Select = component$(
  ({ options, label, input, errors, ...props }: SelectProps) => {
    const { name, required, multiple, placeholder } = props;

    // Create computed value of selected values
    const values = useComputed$(() =>
      Array.isArray(input.value)
        ? input.value
        : input.value && typeof input.value === 'string'
          ? [input.value]
          : []
    );

    return (
      <div class={clsx('px-8 lg:px-10', props.class)}>
        <InputLabel name={name} label={label} required={required} />
        <div class="relative flex items-center">
          <select
            {...props}
            class={clsx(
              'w-full appearance-none space-y-2 rounded-2xl border-2 bg-transparent px-5 outline-none md:text-lg lg:space-y-3 lg:px-6 lg:text-xl',
              errors?.value
                ? 'border-red-600/50 dark:border-red-400/50'
                : 'border-slate-200 hover:border-slate-300 focus:border-sky-600/50 dark:border-slate-800 dark:hover:border-slate-700 dark:focus:border-sky-400/50',
              multiple ? 'py-5' : 'h-14 md:h-16 lg:h-[70px]',
              placeholder && !values.value?.length && 'text-slate-500'
            )}
            id={name}
            aria-invalid={!!errors?.value}
            aria-errormessage={`${name}-error`}
          >
            <option value="" disabled hidden selected={!input.value}>
              {placeholder}
            </option>
            {options.map(({ label, value }) => (
              <option
                key={value}
                value={value}
                selected={values.value?.includes(value)}
              >
                {label}
              </option>
            ))}
          </select>
          {!multiple && (
            <AngleDownIcon class="pointer-events-none absolute right-6 h-5 lg:right-8 lg:h-6" />
          )}
        </div>
        <InputErrors name={name} errors={errors} />
      </div>
    );
  }
);
