// frameworks/react-native/src/hooks/useField/useField.ts
import {
  type FieldElement,
  type FormSchema,
  getFieldBool,
  getFieldInput,
  getFieldStore,
  INTERNAL,
  type RequiredPath,
  setFieldBool,
  setFieldInput,
  validateIfRequired,
  type ValidPath,
} from '@formisch/core/react-native';
import { useMemo, useRef } from 'react';
import type * as v from 'valibot';
import type { FieldStore, FormStore } from '../../types/index.ts';
import { useSignals } from '../useSignals/index.ts';

/**
 * Use field config interface.
 */
export interface UseFieldConfig<
  TSchema extends FormSchema = FormSchema,
  TFieldPath extends RequiredPath = RequiredPath,
> {
  /**
   * The path to the field within the form schema.
   */
  readonly path: ValidPath<v.InferInput<TSchema>, TFieldPath>;
}

/**
 * Creates a reactive field store of a specific field within a form store.
 *
 * @param form The form store instance.
 * @param config The field configuration.
 *
 * @returns The field store with reactive properties and element props.
 */
export function useField<
  TSchema extends FormSchema,
  TFieldPath extends RequiredPath,
>(
  form: FormStore<TSchema>,
  config: UseFieldConfig<TSchema, TFieldPath>
): FieldStore<TSchema, TFieldPath>;

// @__NO_SIDE_EFFECTS__
export function useField(form: FormStore, config: UseFieldConfig): FieldStore {
  useSignals();

  const internalFormStore = form[INTERNAL];
  const internalFieldStore = getFieldStore(internalFormStore, config.path);

  // Track the registered element instance so it can be identified and
  // removed once it detaches, since native elements have no `isConnected`
  // check
  const instanceRef = useRef<FieldElement | null>(null);

  return useMemo(
    () => ({
      path: config.path,
      get input() {
        return getFieldInput(internalFieldStore);
      },
      get errors() {
        return internalFieldStore.errors.value;
      },
      get isTouched() {
        return getFieldBool(internalFieldStore, 'isTouched');
      },
      get isEdited() {
        return getFieldBool(internalFieldStore, 'isEdited');
      },
      get isDirty() {
        return getFieldBool(internalFieldStore, 'isDirty');
      },
      get isValid() {
        return !getFieldBool(internalFieldStore, 'errors');
      },
      onChange(value) {
        setFieldInput(internalFormStore, config.path, value);
        validateIfRequired(internalFormStore, internalFieldStore, 'input');
        validateIfRequired(internalFormStore, internalFieldStore, 'change');
      },
      props: {
        ref(element) {
          if (element) {
            instanceRef.current = element;
            internalFieldStore.elements.push(element);
          } else {
            // Hint: React nulls the ref when the element detaches, whether
            // the field unmounts or the element is swapped while the field
            // stays mounted, so the last known instance is removed here
            const instance = instanceRef.current;
            instanceRef.current = null;
            const elements = internalFieldStore.elements.filter(
              (element) => element !== instance
            );
            // Keep `initialElements` in sync unless a reorder has moved the
            // elements, so resetting a remounted field restores its live
            // element, not a stale one
            if (
              internalFieldStore.elements === internalFieldStore.initialElements
            ) {
              internalFieldStore.initialElements = elements;
            }
            internalFieldStore.elements = elements;
          }
        },
        onFocus() {
          setFieldBool(internalFieldStore, 'isTouched', true);
          validateIfRequired(internalFormStore, internalFieldStore, 'touch');
        },
        onChangeText(text) {
          setFieldInput(internalFormStore, config.path, text);
          validateIfRequired(internalFormStore, internalFieldStore, 'input');
          validateIfRequired(internalFormStore, internalFieldStore, 'change');
        },
        onBlur() {
          validateIfRequired(internalFormStore, internalFieldStore, 'blur');
        },
      },
    }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [internalFormStore, internalFieldStore]
  );
}

// frameworks/qwik/src/hooks/useField/useField.ts
import {
  type FormSchema,
  getElementInput,
  getFieldBool,
  getFieldInput,
  getFieldStore,
  INTERNAL,
  type RequiredPath,
  setFieldBool,
  setFieldInput,
  validateIfRequired,
  type ValidPath,
} from '@formisch/core/qwik';
import {
  $,
  createComputed$,
  useComputed$,
  useConstant,
  useTask$,
} from '@qwik.dev/core';
import type * as v from 'valibot';
import type { FieldStore, FormStore } from '../../types/index.ts';
import { usePathSignal } from '../usePathSignal/index.ts';

/**
 * Use field config interface.
 */
export interface UseFieldConfig<
  TSchema extends FormSchema = FormSchema,
  TFieldPath extends RequiredPath = RequiredPath,
> {
  /**
   * The path to the field within the form schema.
   */
  readonly path: ValidPath<v.InferInput<TSchema>, TFieldPath>;
}

/**
 * Creates a reactive field store of a specific field within a form store.
 *
 * @param form The form store instance.
 * @param config The field configuration.
 *
 * @returns The field store with reactive properties and element props.
 */
export function useField<
  TSchema extends FormSchema,
  TFieldPath extends RequiredPath,
>(
  form: FormStore<TSchema>,
  config: UseFieldConfig<TSchema, TFieldPath>
): FieldStore<TSchema, TFieldPath>;

// @__NO_SIDE_EFFECTS__
export function useField(form: FormStore, config: UseFieldConfig): FieldStore {
  const pathSignal = usePathSignal(config.path);
  const internalFormStore = form[INTERNAL];
  const internalFieldStore = useComputed$(() =>
    getFieldStore(internalFormStore, pathSignal.value)
  );

  useTask$(({ track, cleanup }) => {
    track(internalFieldStore);
    cleanup(() => {
      const internalFieldStoreValue = internalFieldStore.value;
      const elements = internalFieldStoreValue.elements.filter(
        (element) => element.isConnected
      );
      // Keep `initialElements` in sync unless a reorder has moved the elements,
      // so resetting a remounted field restores its live element, not a stale one
      if (
        internalFieldStoreValue.elements ===
        internalFieldStoreValue.initialElements
      ) {
        internalFieldStoreValue.initialElements = elements;
      }
      internalFieldStoreValue.elements = elements;
    });
  });

  return useConstant(() => ({
    path: pathSignal,
    input: createComputed$(() => getFieldInput(internalFieldStore.value)),
    errors: createComputed$(() => internalFieldStore.value.errors.value),
    isTouched: createComputed$(() =>
      getFieldBool(internalFieldStore.value, 'isTouched')
    ),
    isEdited: createComputed$(() =>
      getFieldBool(internalFieldStore.value, 'isEdited')
    ),
    isDirty: createComputed$(() =>
      getFieldBool(internalFieldStore.value, 'isDirty')
    ),
    isValid: createComputed$(
      () => !getFieldBool(internalFieldStore.value, 'errors')
    ),
    onInput: $((value) => {
      setFieldInput(internalFormStore, pathSignal.value, value);
      validateIfRequired(internalFormStore, internalFieldStore.value, 'input');
    }),
    props: {
      get name() {
        return internalFieldStore.value.name;
      },
      autofocus: !!internalFieldStore.value.errors.value,
      ref: $((element) => {
        internalFieldStore.value.elements.push(element);
      }),
      onFocus$: $(() => {
        setFieldBool(internalFieldStore.value, 'isTouched', true);
        validateIfRequired(
          internalFormStore,
          internalFieldStore.value,
          'touch'
        );
      }),
      onInput$: $((_, element) => {
        setFieldInput(
          internalFormStore,
          pathSignal.value,
          getElementInput(element, internalFieldStore.value)
        );
        validateIfRequired(
          internalFormStore,
          internalFieldStore.value,
          'input'
        );
      }),
      onChange$: $(() => {
        validateIfRequired(
          internalFormStore,
          internalFieldStore.value,
          'change'
        );
      }),
      onBlur$: $(() => {
        validateIfRequired(internalFormStore, internalFieldStore.value, 'blur');
      }),
    },
  }));
}
