// playgrounds/react/src/components/UnstyledButton.tsx
import clsx from 'clsx';
import type { ReactNode } from 'react';
import { useState } from 'react';
import { Spinner } from './Spinner';

type LinkProps = {
  type: 'link';
  href: string;
  download?: boolean | string;
  target?: '_blank';
};

type ButtonProps = {
  type: 'button' | 'reset' | 'submit';
  onClick?: () => unknown;
  loading?: boolean;
  form?: string;
};

export type DefaultButtonProps = LinkProps | ButtonProps;

type UnstyledButtonProps = DefaultButtonProps & {
  className?: string;
  'aria-label'?: string;
  children: ReactNode;
};

/**
 * Basic button component that contains important functionality and is used to
 * build more complex components on top of it.
 */
export function UnstyledButton(props: UnstyledButtonProps) {
  // Use loading state
  const [loading, setLoading] = useState(false);

  // Return link button
  if (props.type === 'link') {
    return (
      <a {...props} rel={props.target === '_blank' ? 'noreferrer' : undefined}>
        {props.children}
      </a>
    );
  }

  return (
    <button
      {...props}
      disabled={loading || props.loading}
      // Start and stop loading if function is async
      onClick={
        props.onClick &&
        (async () => {
          setLoading(true);
          await props.onClick!();
          setLoading(false);
        })
      }
    >
      <span
        className={clsx(
          'transition-[opacity,transform,visibility] duration-200',
          loading || props.loading
            ? 'invisible translate-x-5 opacity-0'
            : 'visible delay-300'
        )}
      >
        {props.children}
      </span>
      <span
        className={clsx(
          'absolute duration-200',
          loading || props.loading
            ? 'visible delay-300'
            : 'invisible -translate-x-5 opacity-0'
        )}
      >
        <Spinner />
      </span>
    </button>
  );
}

// website/src/components/UnstyledButton.tsx
import { component$, type QRLEventHandlerMulti, Slot } from '@qwik.dev/core';
import { Link } from './Link';

export type LinkButtonProps = {
  class?: string;
  type: 'link';
  href: string;
  download?: boolean | string;
  target?: '_blank';
};

export type NormalButtonProps = {
  class?: string;
  type: 'button' | 'submit';
  'preventdefault:click'?: boolean;
  onClick$?:
    | ((event: PointerEvent, element: HTMLButtonElement) => any)
    | QRLEventHandlerMulti<PointerEvent, HTMLButtonElement>;
};

export type DefaultButtonProps = LinkButtonProps | NormalButtonProps;

type UnstyledButtonProps = DefaultButtonProps & {
  'aria-label'?: string;
};

/**
 * Basic button component that contains important functionality and is used to
 * build more complex components on top of it.
 */
export const UnstyledButton = component$((props: UnstyledButtonProps) => {
  if (props.type === 'link') {
    // External link
    if (props.target === '_blank') {
      return (
        <a {...props} rel="noreferrer">
          <Slot />
        </a>
      );
    }

    // Internal link
    return (
      <Link {...props}>
        <Slot />
      </Link>
    );
  }

  // Normal button
  return (
    <button {...props}>
      <Slot />
    </button>
  );
});
