// playgrounds/react-native/components/ButtonGroup.tsx
import { clsx } from 'clsx';
import type { ReactNode } from 'react';
import { View } from 'react-native';

type ButtonGroupProps = {
  className?: string;
  children: ReactNode;
};

/**
 * Button group displays multiple related actions side-by-side and helps with
 * arrangement and spacing.
 */
export function ButtonGroup({ children, className }: ButtonGroupProps) {
  return (
    <View
      className={clsx(
        'flex-row flex-wrap gap-6 px-8 lg:gap-8 lg:px-10',
        className
      )}
    >
      {children}
    </View>
  );
}

// playgrounds/angular/src/components/button-group.component.ts
import { Component, input } from '@angular/core';
import clsx from 'clsx';

/**
 * Button group displays multiple related actions side-by-side.
 */
@Component({
  selector: 'app-button-group',
  standalone: true,
  template: `
    <div [class]="classes()">
      <ng-content />
    </div>
  `,
})
export class ButtonGroupComponent {
  readonly class = input<string>('');

  protected readonly classes = () =>
    clsx('flex flex-wrap gap-6 px-8 lg:gap-8 lg:px-10', this.class());
}
