// playgrounds/react-native/components/FormHeader.tsx
import { type FormStore, reset } from '@formisch/react-native';
import { Text, View } from 'react-native';
import { ActionButton } from './ActionButton.tsx';

type FormHeaderProps = {
  of: FormStore;
  heading: string;
  onSubmit: () => Promise<void>;
};

/**
 * Form header with heading and buttons to reset and submit the form.
 *
 * Hint: Unlike the DOM playgrounds the submit handler is passed explicitly,
 * as React Native has no form element with a native submit event.
 */
export function FormHeader({ of: form, heading, onSubmit }: FormHeaderProps) {
  return (
    <View className="flex-row items-center justify-between px-8 lg:px-10">
      <Text className="font-lexend text-2xl text-slate-900 md:text-3xl lg:text-4xl dark:text-slate-200">
        {heading}
      </Text>
      <View className="hidden lg:flex lg:flex-row lg:gap-8">
        <ActionButton
          variant="secondary"
          label="Reset"
          onPress={() => reset(form)}
        />
        <ActionButton variant="primary" label="Submit" onPress={onSubmit} />
      </View>
    </View>
  );
}

// playgrounds/angular/src/components/form-header.component.ts
import { Component, input } from '@angular/core';
import { reset, type FormStore } from '@formisch/angular';
import { ActionButtonComponent } from './action-button.component.ts';

/**
 * Form header with heading and buttons to reset and submit the form.
 */
@Component({
  selector: 'app-form-header',
  standalone: true,
  imports: [ActionButtonComponent],
  template: `
    <header class="flex items-center justify-between px-8 lg:px-10">
      <h1 class="text-2xl text-slate-900 md:text-3xl lg:text-4xl dark:text-slate-200">
        {{ heading() }}
      </h1>
      <div class="hidden lg:flex lg:space-x-8">
        <app-action-button
          variant="secondary"
          label="Reset"
          type="button"
          (clicked)="handleReset()"
        />
        <app-action-button variant="primary" label="Submit" type="submit" />
      </div>
    </header>
  `,
})
export class FormHeaderComponent {
  readonly of = input.required<FormStore>();
  readonly heading = input.required<string>();

  protected handleReset(): void {
    reset(this.of());
  }
}
