// playgrounds/react-native/components/FormFooter.tsx
import { type FormStore, reset } from '@formisch/react-native';
import { View } from 'react-native';
import { ActionButton } from './ActionButton.tsx';

type FormFooterProps = {
  of: FormStore;
  onSubmit: () => Promise<void>;
};

/**
 * Form footer with buttons to reset and submit the form.
 *
 * Hint: Unlike the DOM playgrounds the submit handler is passed explicitly,
 * as React Native has no form element with a native submit event.
 */
export function FormFooter({ of: form, onSubmit }: FormFooterProps) {
  return (
    <View className="flex-row gap-6 px-8 md:gap-8 lg:hidden">
      <ActionButton variant="primary" label="Submit" onPress={onSubmit} />
      <ActionButton
        variant="secondary"
        label="Reset"
        onPress={() => reset(form)}
      />
    </View>
  );
}

// playgrounds/angular/src/components/form-footer.component.ts
import { Component, input } from '@angular/core';
import { reset, type FormStore } from '@formisch/angular';
import { ActionButtonComponent } from './action-button.component.ts';

/**
 * Form footer with buttons to reset and submit the form.
 */
@Component({
  selector: 'app-form-footer',
  standalone: true,
  imports: [ActionButtonComponent],
  template: `
    <footer class="flex space-x-6 px-8 md:space-x-8 lg:hidden">
      <app-action-button variant="primary" label="Submit" type="submit" />
      <app-action-button
        variant="secondary"
        label="Reset"
        type="button"
        (clicked)="handleReset()"
      />
    </footer>
  `,
})
export class FormFooterComponent {
  readonly of = input.required<FormStore>();

  protected handleReset(): void {
    reset(this.of());
  }
}
