// playgrounds/react-native/components/InputErrors.tsx
import { Text } from 'react-native';
import { Expandable } from './Expandable.tsx';

type InputErrorsProps = {
  errors: [string, ...string[]] | null;
};

/**
 * Input error that tells the user what to do to fix the problem.
 */
export function InputErrors({ errors }: InputErrorsProps) {
  return (
    <Expandable expanded={!!errors}>
      <Text className="font-lexend pt-4 text-sm text-red-500 md:text-base lg:pt-5 lg:text-lg dark:text-red-400">
        {errors?.[0]}
      </Text>
    </Expandable>
  );
}

// playgrounds/angular/src/components/input-errors.component.ts
import { Component, input } from '@angular/core';
import { ExpandableComponent } from './expandable.component.ts';

/**
 * Input error that tells the user what to do to fix the problem.
 */
@Component({
  selector: 'app-input-errors',
  standalone: true,
  imports: [ExpandableComponent],
  template: `
    <app-expandable [expanded]="!!errors()">
      <div
        [id]="name() + '-error'"
        class="pt-4 text-sm text-red-500 md:text-base lg:pt-5 lg:text-lg dark:text-red-400"
      >
        {{ errors()?.[0] }}
      </div>
    </app-expandable>
  `,
})
export class InputErrorsComponent {
  readonly name = input.required<string>();
  readonly errors = input<[string, ...string[]] | null>(null);
}
