// playgrounds/qwik/src/components/Slider.tsx
import type { FieldElementProps } from '@formisch/qwik';
import { component$, Signal } from '@qwik.dev/core';
import clsx from 'clsx';
import { InputErrors } from './InputErrors';
import { InputLabel } from './InputLabel';

interface SliderProps extends FieldElementProps {
  class?: string;
  label?: string;
  min?: number;
  max?: number;
  step?: number;
  required?: boolean;
  input: Readonly<Signal<string | number | undefined>>;
  errors: Readonly<Signal<[string, ...string[]] | null>>;
}

/**
 * Range slider that allows users to select predefined numbers. Various
 * decorations can be displayed in or around the field to communicate the
 * entry requirements.
 */
export const Slider = component$(
  ({ label, input, errors, ...props }: SliderProps) => {
    const { name, required } = props;
    return (
      <div class={clsx('px-8 lg:px-10', props.class)}>
        <InputLabel name={name} label={label} required={required} />
        <input
          {...props}
          class="w-full"
          type="range"
          id={name}
          value={input.value}
          aria-invalid={!!errors?.value}
          aria-errormessage={`${name}-error`}
        />
        <InputErrors name={name} errors={errors} />
      </div>
    );
  }
);

// playgrounds/angular/src/components/slider.component.ts
import { Component, computed, input } from '@angular/core';
import { type FieldStore, FormischControl } from '@formisch/angular';
import clsx from 'clsx';
import { InputErrorsComponent } from './input-errors.component.ts';
import { InputLabelComponent } from './input-label.component.ts';

/**
 * Range slider that allows users to select predefined numbers. Various
 * decorations can be displayed in or around the field to communicate the
 * entry requirements.
 */
@Component({
  selector: 'app-slider',
  standalone: true,
  host: { class: 'block' },
  imports: [InputLabelComponent, InputErrorsComponent, FormischControl],
  template: `
    <div [class]="containerClasses()">
      <app-input-label
        [name]="field().name()"
        [label]="label()"
        [required]="required()"
      />
      <input
        class="w-full"
        type="range"
        [id]="field().name()"
        [value]="value()"
        [attr.min]="min()"
        [attr.max]="max()"
        [attr.step]="step()"
        [attr.aria-invalid]="!!field().errors()"
        [attr.aria-errormessage]="
          field().errors() ? field().name() + '-error' : null
        "
        [formischControl]="field()"
      />
      <app-input-errors [name]="field().name()" [errors]="field().errors()" />
    </div>
  `,
})
export class SliderComponent {
  readonly field = input.required<FieldStore<any, any>>();
  readonly label = input<string>();
  readonly min = input<number>();
  readonly max = input<number>();
  readonly step = input<number>();
  readonly required = input<boolean>(false);
  readonly class = input<string>('');

  protected readonly value = computed<string | number>(() => {
    const input = this.field().input();
    return input == null ? '' : (input as string | number);
  });

  protected readonly containerClasses = () =>
    clsx('px-8 lg:px-10', this.class());
}
