// frameworks/vue/src/components/Form/Form.vue
<script setup lang="ts" generic="TSchema extends Schema = Schema">
import {
  INTERNAL,
  type Schema,
  type SubmitEventHandler,
  type SubmitHandler,
} from '@formisch/core/vue';
import { handleSubmit } from '@formisch/methods/vue';
import type { FormStore } from '../../types/index.ts';

/**
 * Form component props interface.
 */
export interface FormProps<TSchema extends Schema = Schema> {
  /**
   * The form store instance.
   */
  of: FormStore<TSchema>;
  /**
   * The submit handler called when the form is submitted and validation succeeds.
   */
  onSubmit: SubmitHandler<TSchema> | SubmitEventHandler<TSchema>;
}

const props = defineProps<FormProps<TSchema>>();

const handler = handleSubmit(props.of, props.onSubmit);
</script>

<template>
  <form
    novalidate
    :ref="
      (element) => {
        of[INTERNAL].element = element as HTMLFormElement;
      }
    "
    @submit="handler"
  >
    <slot></slot>
  </form>
</template>

// frameworks/svelte/src/components/Form/Form.svelte
<script lang="ts" generics="TSchema extends Schema = Schema">
  import {
    INTERNAL,
    type Schema,
    type SubmitHandler,
    type SubmitEventHandler,
  } from '@formisch/core/svelte';
  import { handleSubmit } from '@formisch/methods/svelte';
  import type { FormStore } from '../../types/index.ts';
  import type { Snippet } from 'svelte';
  import type { HTMLFormAttributes } from 'svelte/elements';

  /**
   * Form component props type.
   */
  export type FormProps<TSchema extends Schema = Schema> = Omit<
    HTMLFormAttributes,
    'on:submit' | 'onsubmit' | 'novalidate'
  > & {
    /**
     * The form store instance.
     */
    of: FormStore<TSchema>;
    /**
     * The submit handler called when the form is submitted and validation succeeds.
     */
    onsubmit: SubmitHandler<TSchema> | SubmitEventHandler<TSchema>;
    /**
     * The child elements to render within the form.
     */
    children: Snippet;
  };

  let { of, onsubmit, children, ...other }: FormProps<TSchema> = $props();

  const handler = handleSubmit(of, onsubmit);
</script>

<form {...other} novalidate onsubmit={handler} bind:this={of[INTERNAL].element}>
  {@render children()}
</form>
